apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aks-dns-operator
  annotations:
    lsc-sde.nhs.uk/definitionVersion: "1.0.1"
spec:
  targetNamespace: lscsde
  releaseName: aks-dns-operator
  chart:
    spec:
      chart: aks-dns-operator
      sourceRef:
        kind: HelmRepository
        name: lsc-sde
        namespace: lscsde
  interval: 5m0s
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  valuesFrom:
  - kind: ConfigMap
    name: environment-configs
    key: aks-dns-operator-config.yaml