apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-distributor
  namespace: lscsde-config
  annotations:
    lsc-sde.nhs.uk/definitionVersion: "1.0.1"
spec:
  targetNamespace: secrets-distributor
  releaseName: secrets-distributor
  chart:
    spec:
      chart: secrets-distributor
      version: ${secrets_distributor_chart_version}
      sourceRef:
        kind: HelmRepository
        name: lsc-sde
        namespace: lscsde-config
  interval: 5m0s
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  valuesFrom:
  - kind: ConfigMap
    name: secret-distributor-config